import Image from 'next/image'
import { Inter } from 'next/font/google'
import Head from 'next/head';
import Sidebar from '@/components/Sidebar';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className="bg-white">
      <Head>
        <title>
          Create Next App
        </title>
        <meta name="description" content = "Generated by create next app"/>
        <link rel = "icon" href="/favicon.ico" />
      </Head>

      <div className=""> 
        {/* Sidebar */}

        <Sidebar />
        {/* Feed */}
        {/* Widgets */}
      </div>
    </div>
  );
}
